- name: "Set superset config configured."
  template:
    src: "superset_python_path/superset_config.py.j2"
    dest: "{{ superset_config_module_path }}"
    owner: "{{ superset_user }}"
    group: "{{ superset_group }}"
  notify:
    - restart superset

- name: Create an admin user.
  become: true
  become_user: "{{ superset_user }}"
  shell: "export PYTHONPATH='{{ superset_python_path }}' && export FLASK_APP='{{ superset_app }}' && {{ superset_virtualenv_path }}/bin/flask fab create-admin --username {{ superset_username }} --firstname {{ superset_firstname }}  --lastname {{ superset_lastname }}  --email {{ superset_email }} --password {{ superset_pass }}"

- name: Upgrade the superset db.
  become: true
  become_user: "{{ superset_user }}"
  shell: "export PYTHONPATH='{{ superset_python_path }}' && {{ superset_virtualenv_path }}/bin/superset db upgrade"

- name: Load superset examples.
  become: true
  become_user: "{{ superset_user }}"
  shell: "export PYTHONPATH='{{ superset_python_path }}' && {{ superset_virtualenv_path }}/bin/superset load_examples"
  when: superset_load_examples

- name: Superset init.
  become: true
  become_user: "{{ superset_user }}"
  shell: "export PYTHONPATH='{{ superset_python_path }}' && {{ superset_virtualenv_path }}/bin/superset init"

- name: Create superset systemd service
  template:
    src: "superset.service.j2"
    dest: "{{ superset_service }}"
    owner: root
    group: root
    mode: 644
  notify:
    - reload systemctl
    - restart superset

- name: Ensure Superset is running
  service:
    name: superset
    state: started
    enabled: yes
  when: superset_check_if_running

- name: Ensure Superset is restarted
  service:
    name: superset
    state: restarted
  when: superset_force_restart

